OscarCreator/rsync.nvim

.github/workflows/lint.yml, .luacheckrc, .stylua.toml, Makefile, lua/rsync/config.lua, lua/rsync/init.lua
=> Added actions for lua lints

README.md, lua/rsync/config.lua, lua/rsync/init.lua
=> Added RsyncUp command

autoload/health/rsync.lua, lua/rsync/health.lua
=> Added health checks

lua/rsync/health.lua
=> Added health check for older versions or rsync

.luacheckrc, lua/rsync/init.lua, lua/rsync/project.lua
This moves config file functionality to project.lua and caches already loaded configs
This solves #20
=> Save configs in global table

lua/rsync/config.lua, lua/rsync/init.lua, lua/rsync/project.lua, lua/rsync/sync.lua
This fixes #20, fixes #6, fixes #18
=> One job syncing at a time

.github/workflows/busted.yml, Makefile, scripts/minimal.vim, tests/minimal_init.lua, tests/rsync/rsync_spec.lua, tests/rsync_helper.lua
=> Added test using plenary.nvim

lua/rsync/init.lua, lua/rsync/sync.lua, tests/rsync/rsync_spec.lua
=> Added command to sync down only current file

.github/workflows/lint.yml, lua/rsync/sync.lua, tests/rsync/rsync_spec.lua, tests/rsync_helper.lua
=> Delete files no longer on local

README.md, lua/rsync/init.lua, lua/rsync/project.lua, lua/rsync/sync.lua, tests/rsync/rsync_spec.lua, tests/rsync_helper.lua
This adds RsyncUpFile command and fixes #35.
=> Added RsyncUpFile command

.gitignore, README.md, doc/rsync.txt
=> Added documentation

README.md
=> Added code coverage badge to README.md

README.md
=> Added simple gif

doc/rsync.txt
This adds nvim docs for RsyncLog command
=> Added doc's for RsyncLog

README.md
=> added RsyncLog to README.md

README.md, doc/rsync.txt, lua/rsync/config.lua, lua/rsync/init.lua, tests/rsync/rsync_spec.lua
=> Sync when git repo have changed

lua/rsync/sync.lua, tests/rsync/rsync_spec.lua, tests/rsync_helper.lua
=> Added support for `!` statement's in .gitignore

lua/rsync/init.lua
=> change vim.print to vim.inspect to increase backwards compatibility

README.md
=> Fix missing comma in installation guide

.github/workflows/busted.yml, Makefile
=> Fix building on macos

lua/rsync/init.lua
=> Fix RsyncDownFile not expanding with relative modifier

Makefile, lua/rsync/init.lua, tests/rsync/rsync_spec.lua
=> Added optional argument to the per file sync commands

README.md, doc/rsync.txt
=> Updated docs for optional per file sync commands

doc/rsync.txt, lua/rsync/config.lua, lua/rsync/sync.lua
Also added a new config reload_file_after_sync. This closes #13
=> Added docs for all config options.

README.md, doc/rsync.txt, lua/rsync/init.lua, tests/rsync/rsync_spec.lua
=> Added command to temporarily disable sync on save

README.md, doc/rsync.txt, lua/rsync/project.lua, lua/rsync/sync.lua, tests/rsync/rsync_spec.lua
=> Support multiple ignore files (address #29)

README.md
I've noticed that our projects share some similarities, and I believe it would be beneficial to exchange GitHub links through a 'Similar Projects' section. 
Looking forward to your response.
Best regards!
=> docs: add similar projects section
